"use client";
import { useMemo, useState } from "react";
import { Check, ChevronLeft, ChevronRight, LockKeyhole, Send } from "lucide-react";

type Item={id:string;name:string}; type Q={id:string;text:string;analyticsCode:string|null;type:string;required:boolean};
type Props={data:{survey:{id:string;slug:string;title:string;currentVersion:{id:string;version:number;anonymityMode:"ANONYMOUS"|"IDENTIFIED";sections:{id:string;title:string;questions:Q[]}[]}};departments:Item[];projects:Item[];roles:Item[];formats:Item[];directions:Item[]}};
const steps=["Старт","Контекст","Общая оценка","Сотрудничество","Направления","Комментарии","Проверка"];

export default function SurveyWizard({data}:Props){
 const [step,setStep]=useState(0); const [sending,setSending]=useState(false); const [done,setDone]=useState(false); const [error,setError]=useState(""); const [idempotencyKey]=useState(()=>crypto.randomUUID());
 const [context,setContext]=useState({departmentId:"",projectId:"",roleId:"",formatId:"",interactionStart:"",interactionEnd:"",directionIds:[] as string[],respondentName:"",respondentEmail:"",contactConsent:false});
 const [answers,setAnswers]=useState<Record<string,{numericValue?:number|null;textValue?:string|null;notApplicable?:boolean}>>({});
 const sections=data.survey.currentVersion.sections; const general=useMemo(()=>sections.find(s=>s.title==="Общая оценка")?.questions??[],[sections]); const collab=useMemo(()=>sections.find(s=>s.title==="Качество сотрудничества")?.questions??[],[sections]); const directionQ=sections.find(s=>s.title==="Выбранные направления")?.questions??[]; const comments=sections.find(s=>s.title==="Комментарии")?.questions??[];
 const identified=data.survey.currentVersion.anonymityMode==="IDENTIFIED"; const progress=((step+1)/steps.length)*100;
 const name=(items:Item[],id:string)=>items.find(i=>i.id===id)?.name??"—";
 const valid=useMemo(()=>{if(step===1)return !!(context.departmentId&&context.projectId&&context.roleId&&context.formatId&&context.interactionStart&&context.interactionEnd&&context.directionIds.length&&(!identified||(context.respondentName&&context.respondentEmail)));if(step===2)return general.every(q=>answers[q.id]?.numericValue!==undefined);if(step===3)return collab.filter(q=>q.required).every(q=>answers[q.id]?.numericValue!==undefined||answers[q.id]?.notApplicable);return true},[step,context,answers,identified,general,collab]);
 const next=()=>{setError("");if(!valid){setError("Заполните обязательные поля, чтобы продолжить.");return}setStep(s=>Math.min(steps.length-1,s+1));window.scrollTo({top:0,behavior:"smooth"})};
 const submit=async()=>{setSending(true);setError("");try{const res=await fetch("/api/responses",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({surveyId:data.survey.id,surveyVersionId:data.survey.currentVersion.id,idempotencyKey,anonymityMode:data.survey.currentVersion.anonymityMode,...context,respondentName:identified?context.respondentName:undefined,respondentEmail:identified?context.respondentEmail:undefined,answers:Object.entries(answers).map(([questionId,v])=>({questionId,...v}))})});const body=await res.json();if(!res.ok)throw new Error(body.error||"Не удалось отправить ответ");setDone(true)}catch(e){setError(e instanceof Error?e.message:"Системная ошибка")}finally{setSending(false)}};
 const Scale=({q,max=5,na=false}:{q:Q;max?:number;na?:boolean})=><div className="question-line"><div className="label">{q.text}{q.required&&<span aria-label="обязательно"> *</span>}</div><div className="scale-row" role="radiogroup" aria-label={q.text}>{Array.from({length:max+1-(max===5?1:0)},(_,i)=>i+(max===5?1:0)).map(v=><label className="scale-option" key={v}><input type="radio" name={q.id} checked={answers[q.id]?.numericValue===v} onChange={()=>setAnswers(a=>({...a,[q.id]:{numericValue:v,notApplicable:false}}))}/><span>{v}</span></label>)}{na&&<label className="scale-option"><input type="radio" name={q.id} checked={answers[q.id]?.notApplicable===true} onChange={()=>setAnswers(a=>({...a,[q.id]:{numericValue:null,notApplicable:true}}))}/><span style={{width:"auto",padding:"0 12px"}}>Не применимо</span></label>}</div></div>;
 if(done)return <main className="survey-shell"><header className="survey-header"><div className="brand"><span className="brandmark">PO</span> Process Office</div></header><div className="survey-main"><div className="card question-card"><div className="success-icon"><Check/></div><div className="eyebrow">Ответ принят</div><h1>Спасибо за обратную связь!</h1><p className="muted">Ваш ответ сохранён. Результаты будут использованы для улучшения работы процессного офиса.</p><button className="button" style={{marginTop:24}} onClick={()=>window.location.assign(`/s/${data.survey.slug}`)}>На главную</button></div></div></main>;
 return <main className="survey-shell"><header className="survey-header"><div className="brand"><span className="brandmark">PO</span> Process Office</div><span className="hint">Версия {data.survey.currentVersion.version}</span></header><div className="survey-main"><div className="progress-row"><div className="progress"><span style={{width:`${progress}%`}}/></div><span className="hint">{step+1} из {steps.length}</span></div><div className="card question-card">
 {step===0&&<><div className="eyebrow">Обратная связь</div><h1>{data.survey.title}</h1><p className="muted">Помогите нам понять, что работает хорошо и где мы можем стать полезнее. Заполнение займёт 7–10 минут.</p><div className="notice"><LockKeyhole size={18} style={{float:"left",marginRight:9}}/><b>{identified?"Идентифицированный опрос":"Анонимный опрос"}</b><br/>{identified?"Мы запросим имя и рабочий email. Контакт для уточнения используется только с отдельного согласия.":"Мы не запрашиваем и не сохраняем имя, email, user ID или IP. Проект, подразделение, роль и период могут косвенно раскрыть автора."}</div></>}
 {step===1&&<div className="stack"><div><div className="eyebrow">Шаг 2</div><h2>Контекст взаимодействия</h2><p className="muted">Расскажите, с какой задачей вы обращались.</p></div>{identified&&<div className="grid2"><div className="field"><label>Имя *</label><input value={context.respondentName} onChange={e=>setContext(c=>({...c,respondentName:e.target.value}))}/></div><div className="field"><label>Рабочий email *</label><input type="email" value={context.respondentEmail} onChange={e=>setContext(c=>({...c,respondentEmail:e.target.value}))}/></div></div>}<div className="grid2"><Select label="Подразделение *" items={data.departments} value={context.departmentId} set={v=>setContext(c=>({...c,departmentId:v}))}/><Select label="Проект или инициатива *" items={data.projects} value={context.projectId} set={v=>setContext(c=>({...c,projectId:v}))}/><Select label="Роль в проекте *" items={data.roles} value={context.roleId} set={v=>setContext(c=>({...c,roleId:v}))}/><Select label="Формат сотрудничества *" items={data.formats} value={context.formatId} set={v=>setContext(c=>({...c,formatId:v}))}/><div className="field"><label>Начало взаимодействия *</label><input type="date" value={context.interactionStart} onInput={e=>{const value=e.currentTarget.value;setContext(c=>({...c,interactionStart:value}))}}/></div><div className="field"><label>Окончание взаимодействия *</label><input type="date" value={context.interactionEnd} onInput={e=>{const value=e.currentTarget.value;setContext(c=>({...c,interactionEnd:value}))}}/></div></div><div><div className="label" style={{marginBottom:10}}>Направления работы *</div><div className="check-grid">{data.directions.map(d=><label key={d.id} className="check-tile"><input type="checkbox" checked={context.directionIds.includes(d.id)} onChange={e=>setContext(c=>({...c,directionIds:e.target.checked?[...c.directionIds,d.id]:c.directionIds.filter(id=>id!==d.id)}))}/><span>{d.name}</span></label>)}</div></div></div>}
 {step===2&&<><div className="eyebrow">Шаг 3</div><h2>Общая оценка</h2><p className="muted">Оценки не выбраны по умолчанию.</p>{general.map(q=><Scale key={q.id} q={q} max={q.type==="SCALE_0_10"?10:5}/>)}</>}
 {step===3&&<><div className="eyebrow">Шаг 4</div><h2>Качество сотрудничества</h2><p className="muted">Если критерий не относился к вашей работе, выберите «Не применимо».</p>{collab.map(q=><Scale key={q.id} q={q} na/>)}</>}
 {step===4&&<><div className="eyebrow">Шаг 5</div><h2>Выбранные направления</h2><p className="muted">Оцените результат по направлениям: {context.directionIds.map(id=>name(data.directions,id)).join(", ")}.</p>{directionQ.map(q=><Scale key={q.id} q={q} na/>)}</>}
 {step===5&&<><div className="eyebrow">Шаг 6</div><h2>Комментарии</h2><p className="muted">Не указывайте персональные данные или конфиденциальную информацию.</p><div className="stack" style={{marginTop:20}}>{comments.map(q=><div className="field" key={q.id}><label>{q.text}</label><textarea maxLength={2000} value={answers[q.id]?.textValue??""} onChange={e=>setAnswers(a=>({...a,[q.id]:{textValue:e.target.value}}))}/><span className="hint">До 2000 символов</span></div>)}</div></>}
 {step===6&&<><div className="eyebrow">Шаг 7</div><h2>Проверьте ответ</h2><p className="muted">После отправки изменить ответ будет нельзя.</p><div className="notice"><b>{name(data.departments,context.departmentId)}</b><br/>{name(data.projects,context.projectId)} · {name(data.roles,context.roleId)}<br/>{context.interactionStart} — {context.interactionEnd}</div><div className="stack"><div><b>Направления</b><p className="muted">{context.directionIds.map(id=>name(data.directions,id)).join(", ")}</p></div><div><b>Общая удовлетворённость</b><p className="muted">{answers[general[0]?.id]?.numericValue??"—"} из 5</p></div></div></>}
 {error&&<div className="error" role="alert" style={{marginTop:18}}>{error}</div>}<div className="actions">{step>0?<button className="button secondary" onClick={()=>setStep(s=>s-1)}><ChevronLeft size={17}/>Назад</button>:<span/>}{step<steps.length-1?<button className="button" onClick={next}>Продолжить<ChevronRight size={17}/></button>:<button className="button" onClick={submit} disabled={sending}>{sending?"Отправляем…":<><Send size={17}/>Отправить ответ</>}</button>}</div>
 </div></div></main>
}
function Select({label,items,value,set}:{label:string;items:Item[];value:string;set:(v:string)=>void}){return <div className="field"><label>{label}</label><select value={value} onChange={e=>set(e.target.value)}><option value="">Выберите</option>{items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></div>}
