import ExcelJS from "exceljs";
import { prisma } from "./prisma";
import { analyticsData, responseWhere, type Filters } from "./data";
import { safeCell } from "./validation";

export async function exportRows(filters:Filters){return prisma.surveyResponse.findMany({where:responseWhere(filters,true),include:{survey:true,surveyVersion:true,answers:true,directions:true},orderBy:{submittedAt:"desc"}})}
const summaryRow=(r:Awaited<ReturnType<typeof exportRows>>[number])=>({"ID ответа":r.id,"Опрос":safeCell(r.survey.title),"Версия":r.surveyVersion.version,"Дата отправки":r.submittedAt?.toISOString()??"","Статус":r.status,"Анонимность":r.anonymityMode,"Подразделение":safeCell(r.departmentSnapshot),"Проект":safeCell(r.projectSnapshot),"Роль":safeCell(r.roleSnapshot),"Формат":safeCell(r.formatSnapshot),"Направления":safeCell(r.directions.map(d=>d.directionSnapshot).join("; ")),"Имя":safeCell(r.respondentName),"Email":safeCell(r.respondentEmail)});
export function csvBuffer(rows:Awaited<ReturnType<typeof exportRows>>){const data=rows.map(summaryRow);const headers=Object.keys(data[0]??summaryRow({id:"",survey:{title:""},surveyVersion:{version:0},submittedAt:null,status:"",anonymityMode:"",departmentSnapshot:"",projectSnapshot:"",roleSnapshot:"",formatSnapshot:"",directions:[],respondentName:null,respondentEmail:null} as never));const esc=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;return Buffer.from(`\uFEFF${headers.map(esc).join(",")}\r\n${data.map(row=>headers.map(h=>esc(row[h as keyof typeof row])).join(",")).join("\r\n")}`,"utf8")}
export async function xlsxBuffer(rows:Awaited<ReturnType<typeof exportRows>>,filters:Filters){const wb=new ExcelJS.Workbook();wb.creator="Process Office Feedback";wb.created=new Date();const add=(name:string,data:Record<string,unknown>[])=>{const ws=wb.addWorksheet(name);if(!data.length){ws.addRow(["Нет данных"]);return ws}const headers=Object.keys(data[0]);ws.columns=headers.map(h=>({header:h,key:h,width:Math.min(45,Math.max(14,h.length+3))}));data.forEach(r=>ws.addRow(r));ws.getRow(1).font={bold:true,color:{argb:"FFFFFFFF"}};ws.getRow(1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF2764E7"}};ws.autoFilter={from:"A1",to:{row:1,column:headers.length}};ws.views=[{state:"frozen",ySplit:1}];return ws};add("Ответы",rows.map(summaryRow));add("Ответы_детально",rows.flatMap(r=>r.answers.map(a=>({"ID ответа":r.id,"Код вопроса":a.questionCodeSnapshot??"","Вопрос":safeCell(a.questionTextSnapshot),"Тип":a.questionTypeSnapshot,"Значение":safeCell(a.textValue??a.numericValue),"Не применимо":a.notApplicable?"Да":"Нет","Статус":r.status}))));const {metrics}=await analyticsData(filters);add("Метрики",Object.entries(metrics).map(([k,v])=>({"Метрика":k,"Значение":v??"Нет данных"})));add("Комментарии",rows.flatMap(r=>r.answers.filter(a=>a.textValue).map(a=>({"Дата":r.submittedAt?.toISOString()??"","Проект":safeCell(r.projectSnapshot),"Код":a.questionCodeSnapshot??"","Комментарий":safeCell(a.textValue),"Статус":r.status}))));const [deps,projects,formats,directions]=await Promise.all([prisma.department.findMany(),prisma.project.findMany(),prisma.collaborationFormat.findMany(),prisma.processOfficeDirection.findMany()]);add("Справочники",[...deps.map(x=>({"Тип":"Подразделение","Значение":safeCell(x.name),"Активно":x.active?"Да":"Нет"})),...projects.map(x=>({"Тип":"Проект","Значение":safeCell(x.name),"Активно":x.active?"Да":"Нет"})),...formats.map(x=>({"Тип":"Формат","Значение":safeCell(x.name),"Активно":x.active?"Да":"Нет"})),...directions.map(x=>({"Тип":"Направление","Значение":safeCell(x.name),"Активно":x.active?"Да":"Нет"}))]);add("Метаданные",[{"Параметр":"Дата формирования UTC","Значение":new Date().toISOString()},{"Параметр":"Фильтры","Значение":safeCell(JSON.stringify(filters))},{"Параметр":"Строк ответов","Значение":rows.length},{"Параметр":"Примечание","Значение":"INVALIDATED включены в первичные данные, но исключены из метрик"}]);return Buffer.from(await wb.xlsx.writeBuffer())}
